package/iputils: Bump to version s20190709
Add 's' before release as this is in upstream tags and in sha256sum.asc.
This prevents error:
ERROR: No hash found for iputils-20190709.tar.gz

Remove all patches (accepted in this release).

Signed-off-by: Petr Vorel <petr.vorel@gmail.com>